[package]
name = "advent_of_code_2024"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"

[[bin]]
name = "day_01"
path = "src/day_01/day_01.rs"

[[bin]]
name = "day_02"
path = "src/day_02/day_02.rs"

[[bin]]
name = "day_03"
path = "src/day_03/day_03.rs"
